"""Canonical technology vocabulary used for deterministic matching."""

SKILL_ALIASES = {
    "html": ("html", "html5"),
    "css": ("css", "css3", "scss", "sass"),
    "javascript": ("javascript", "ecmascript", "js"),
    "typescript": ("typescript", "ts"),
    "react.js": ("react", "reactjs", "react.js"),
    "next.js": ("nextjs", "next.js", "next js"),
    "node.js": ("node", "nodejs", "node.js", "node js"),
    "python": ("python", "django", "flask", "fastapi"),
    "java": ("java", "spring boot", "spring"),
    "c++": ("c++", "cpp"),
    "c": ("c programming", "language c"),
    "c#": ("c#", "csharp", ".net", "dotnet"),
    "php": ("php", "laravel"),
    "sql": ("sql", "sqlite"),
    "nosql": ("nosql", "no sql"),
    "mysql": ("mysql", "my sql"),
    "postgresql": ("postgres", "postgresql", "postgre sql"),
    "mongodb": ("mongodb", "mongo db", "mongo"),
    "redis": ("redis",),
    "firebase": ("firebase", "firestore"),
    "database": ("database", "dbms", "rdbms"),
    "git": ("git",),
    "github": ("github", "git hub"),
    "rest api": ("rest api", "restful api", "restful", "rest apis"),
    "graphql": ("graphql", "graph ql"),
    "json": ("json",),
    "postman": ("postman",),
    "swagger": ("swagger", "openapi", "open api"),
    "docker": ("docker", "containerization", "containers"),
    "kubernetes": ("kubernetes", "k8s"),
    "aws": ("aws", "amazon web services"),
    "azure": ("azure", "microsoft azure"),
    "gcp": ("gcp", "google cloud"),
    "jwt": ("jwt", "json web token"),
    "oauth": ("oauth", "oauth2", "oauth 2.0"),
    "api key authentication": ("api key", "api-key", "x-api-key"),
    "webhooks": ("webhook", "webhooks"),
    "api documentation": ("api documentation", "api docs", "technical documentation"),
    "redux": ("redux", "redux toolkit"),
    "zustand": ("zustand",),
    "jest": ("jest",),
    "responsive design": ("responsive design", "responsive", "media queries"),
    "ci/cd": ("ci/cd", "cicd", "continuous integration", "continuous deployment"),
    "deployment": ("deployment", "deploy", "vercel", "netlify", "render.com"),
    "linux": ("linux", "unix"),
    "pandas": ("pandas",),
    "numpy": ("numpy",),
    "machine learning": ("machine learning", "ml", "scikit-learn", "sklearn"),
    "figma": ("figma",),
    "tailwind css": ("tailwind", "tailwindcss", "tailwind css"),
    "bootstrap": ("bootstrap",),
    "angular": ("angular", "angularjs"),
    "vue.js": ("vue", "vuejs", "vue.js"),
    "express.js": ("express", "expressjs", "express.js"),
    "schema design": ("schema design", "database schema", "normalization", "normalisation"),
    "query optimization": ("query optimization", "query optimisation", "sql optimization", "sql optimisation"),
    "indexing": ("indexing", "database indexing", "indexes", "indices"),
    "stored procedures": ("stored procedure", "stored procedures"),
    "aggregation pipelines": ("aggregation pipeline", "aggregation pipelines", "aggregate pipeline"),
    "erd design": ("erd", "entity relationship diagram", "er diagram"),
    "third-party sdk": ("third party sdk", "third-party sdk", "sdk integration"),
}

PARTIAL_RELATIONS = {
    "sql": {"mysql", "postgresql"},
    "database": {"sql", "nosql", "mysql", "postgresql", "mongodb", "redis", "firebase"},
    "cloud": {"aws", "azure", "gcp", "firebase"},
    "authentication": {"jwt", "oauth", "api key authentication"},
    "backend language": {"node.js", "python", "java", "php", "c#"},
}
